"""initial

Revision ID: 728134cbd823
Revises: 
Create Date: 2025-03-31 01:08:25.145602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '728134cbd823'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('priority', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # op.alter_column('tasks', 'status',
    #            existing_type=sa.VARCHAR(length=19),
    #            type_=sa.Enum('NEW', 'IN_PROGRESS', 'FINISH', name='taskstatus'),
    #            existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('tasks', 'status',
    #            existing_type=sa.Enum('NEW', 'IN_PROGRESS', 'FINISH', name='taskstatus'),
    #            type_=sa.VARCHAR(length=19),
    #            existing_nullable=True)
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'created_at')
    op.drop_column('tasks', 'priority')
    # ### end Alembic commands ###
